// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type projectsTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *projectsTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("Projects").
func (v *projectsTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *projectsTableType) Columns() []string {
	return []string{
		"Id",
		"ParentId",
		"ProjectName",
		"ProjectDescription",
		"CreationDate",
		"OwnerId",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *projectsTableType) NewStruct() reform.Struct {
	return new(Projects)
}

// NewRecord makes a new record for that table.
func (v *projectsTableType) NewRecord() reform.Record {
	return new(Projects)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *projectsTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// ProjectsTable represents Projects view or table in SQL database.
var ProjectsTable = &projectsTableType{
	s: parse.StructInfo{
		Type:    "Projects",
		SQLName: "Projects",
		Fields: []parse.FieldInfo{
			{Name: "Id", Type: "uuid.UUID", Column: "Id"},
			{Name: "ParentId", Type: "uuid.UUID", Column: "ParentId"},
			{Name: "ProjectName", Type: "string", Column: "ProjectName"},
			{Name: "ProjectDescription", Type: "*string", Column: "ProjectDescription"},
			{Name: "CreationDate", Type: "time.Time", Column: "CreationDate"},
			{Name: "OwnerId", Type: "uuid.UUID", Column: "OwnerId"},
		},
		PKFieldIndex: 0,
	},
	z: new(Projects).Values(),
}

// String returns a string representation of this struct or record.
func (s Projects) String() string {
	res := make([]string, 6)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "ParentId: " + reform.Inspect(s.ParentId, true)
	res[2] = "ProjectName: " + reform.Inspect(s.ProjectName, true)
	res[3] = "ProjectDescription: " + reform.Inspect(s.ProjectDescription, true)
	res[4] = "CreationDate: " + reform.Inspect(s.CreationDate, true)
	res[5] = "OwnerId: " + reform.Inspect(s.OwnerId, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Projects) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.ParentId,
		s.ProjectName,
		s.ProjectDescription,
		s.CreationDate,
		s.OwnerId,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Projects) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.ParentId,
		&s.ProjectName,
		&s.ProjectDescription,
		&s.CreationDate,
		&s.OwnerId,
	}
}

// View returns View object for that struct.
func (s *Projects) View() reform.View {
	return ProjectsTable
}

// Table returns Table object for that record.
func (s *Projects) Table() reform.Table {
	return ProjectsTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Projects) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Projects) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Projects) HasPK() bool {
	return s.Id != ProjectsTable.z[ProjectsTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Id = pk.
func (s *Projects) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = ProjectsTable
	_ reform.Struct = (*Projects)(nil)
	_ reform.Table  = ProjectsTable
	_ reform.Record = (*Projects)(nil)
	_ fmt.Stringer  = (*Projects)(nil)
)

func init() {
	parse.AssertUpToDate(&ProjectsTable.s, new(Projects))
}
