// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: columns.proto

package web

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// swagger:model
type Column struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Id колонки
	// Required: true
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Имя колонки
	// Required: true
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Column) Reset() {
	*x = Column{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{0}
}

func (x *Column) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// swagger:model
type ColumnUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// структура обновляемой колонки
	// Required: true
	Column *Column `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *ColumnUpdateRequest) Reset() {
	*x = ColumnUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnUpdateRequest) ProtoMessage() {}

func (x *ColumnUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnUpdateRequest.ProtoReflect.Descriptor instead.
func (*ColumnUpdateRequest) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{1}
}

func (x *ColumnUpdateRequest) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

// swagger:model
type ColumnUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ColumnUpdateResponse) Reset() {
	*x = ColumnUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnUpdateResponse) ProtoMessage() {}

func (x *ColumnUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnUpdateResponse.ProtoReflect.Descriptor instead.
func (*ColumnUpdateResponse) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{2}
}

func (x *ColumnUpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// swagger:model
type ColumnCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// имя колонки
	// Required: true
	// Example: To Do
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *ColumnCreateRequest) Reset() {
	*x = ColumnCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnCreateRequest) ProtoMessage() {}

func (x *ColumnCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnCreateRequest.ProtoReflect.Descriptor instead.
func (*ColumnCreateRequest) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{3}
}

func (x *ColumnCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// swagger:model
type ColumnCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Column *Column `protobuf:"bytes,1,opt,name=column,proto3" json:"column,omitempty"`
}

func (x *ColumnCreateResponse) Reset() {
	*x = ColumnCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnCreateResponse) ProtoMessage() {}

func (x *ColumnCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnCreateResponse.ProtoReflect.Descriptor instead.
func (*ColumnCreateResponse) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{4}
}

func (x *ColumnCreateResponse) GetColumn() *Column {
	if x != nil {
		return x.Column
	}
	return nil
}

// swagger:model
type ColumnDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// id удаляемой колонки
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ColumnDeleteRequest) Reset() {
	*x = ColumnDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDeleteRequest) ProtoMessage() {}

func (x *ColumnDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDeleteRequest.ProtoReflect.Descriptor instead.
func (*ColumnDeleteRequest) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{5}
}

func (x *ColumnDeleteRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// swagger:model
type ColumnDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
}

func (x *ColumnDeleteResponse) Reset() {
	*x = ColumnDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnDeleteResponse) ProtoMessage() {}

func (x *ColumnDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnDeleteResponse.ProtoReflect.Descriptor instead.
func (*ColumnDeleteResponse) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{6}
}

func (x *ColumnDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// swagger:model
type ColumnsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Список всех колонок
	Columns []*Column `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
}

func (x *ColumnsListResponse) Reset() {
	*x = ColumnsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_columns_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ColumnsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ColumnsListResponse) ProtoMessage() {}

func (x *ColumnsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_columns_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ColumnsListResponse.ProtoReflect.Descriptor instead.
func (*ColumnsListResponse) Descriptor() ([]byte, []int) {
	return file_columns_proto_rawDescGZIP(), []int{7}
}

func (x *ColumnsListResponse) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

var File_columns_proto protoreflect.FileDescriptor

var file_columns_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0c, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65, 0x72, 0x22, 0x2c, 0x0a,
	0x06, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x13, 0x43,
	0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x72, 0x61, 0x63, 0x6b, 0x65,
	0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x22, 0x30, 0x0a, 0x14, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x22, 0x29, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a,
	0x14, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2c, 0x0a, 0x06, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x72, 0x61,
	0x63, 0x6b, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x06, 0x63, 0x6f, 0x6c,
	0x75, 0x6d, 0x6e, 0x22, 0x25, 0x0a, 0x13, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x30, 0x0a, 0x14, 0x43, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x22, 0x45, 0x0a, 0x13,
	0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x74, 0x61, 0x73, 0x6b, 0x5f, 0x74, 0x72, 0x61, 0x63,
	0x6b, 0x65, 0x72, 0x2e, 0x43, 0x6f, 0x6c, 0x75, 0x6d, 0x6e, 0x52, 0x07, 0x63, 0x6f, 0x6c, 0x75,
	0x6d, 0x6e, 0x73, 0x42, 0x07, 0x5a, 0x05, 0x2e, 0x2f, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_columns_proto_rawDescOnce sync.Once
	file_columns_proto_rawDescData = file_columns_proto_rawDesc
)

func file_columns_proto_rawDescGZIP() []byte {
	file_columns_proto_rawDescOnce.Do(func() {
		file_columns_proto_rawDescData = protoimpl.X.CompressGZIP(file_columns_proto_rawDescData)
	})
	return file_columns_proto_rawDescData
}

var file_columns_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_columns_proto_goTypes = []interface{}{
	(*Column)(nil),               // 0: task_tracker.Column
	(*ColumnUpdateRequest)(nil),  // 1: task_tracker.ColumnUpdateRequest
	(*ColumnUpdateResponse)(nil), // 2: task_tracker.ColumnUpdateResponse
	(*ColumnCreateRequest)(nil),  // 3: task_tracker.ColumnCreateRequest
	(*ColumnCreateResponse)(nil), // 4: task_tracker.ColumnCreateResponse
	(*ColumnDeleteRequest)(nil),  // 5: task_tracker.ColumnDeleteRequest
	(*ColumnDeleteResponse)(nil), // 6: task_tracker.ColumnDeleteResponse
	(*ColumnsListResponse)(nil),  // 7: task_tracker.ColumnsListResponse
}
var file_columns_proto_depIdxs = []int32{
	0, // 0: task_tracker.ColumnUpdateRequest.column:type_name -> task_tracker.Column
	0, // 1: task_tracker.ColumnCreateResponse.column:type_name -> task_tracker.Column
	0, // 2: task_tracker.ColumnsListResponse.columns:type_name -> task_tracker.Column
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_columns_proto_init() }
func file_columns_proto_init() {
	if File_columns_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_columns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Column); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_columns_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ColumnsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_columns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_columns_proto_goTypes,
		DependencyIndexes: file_columns_proto_depIdxs,
		MessageInfos:      file_columns_proto_msgTypes,
	}.Build()
	File_columns_proto = out.File
	file_columns_proto_rawDesc = nil
	file_columns_proto_goTypes = nil
	file_columns_proto_depIdxs = nil
}
