basePath: /api/v1
host: localhost:8080
info:
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: json
      summary: Get all tags
      tags:
      - Tag
swagger: "2.0"
