basePath: /api/v1
definitions:
  models.Tag:
    properties:
      color:
        example: ffffff
        type: string
      id:
        example: 550e8400-e29b-41d4-a716-446655440000
        format: uuid
        type: string
      name:
        example: tag name
        type: string
    type: object
host: localhost:8080
info:
  version: v1
  title: title
  contact: {}
paths:
  /:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Tag'
            type: array
      summary: Get all tags
      tags:
      - Tag
swagger: "2.0"
