// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type tasksTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *tasksTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("Tasks").
func (v *tasksTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *tasksTableType) Columns() []string {
	return []string{
		"Id",
		"ProjectId",
		"TaskTitle",
		"TaskDescription",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *tasksTableType) NewStruct() reform.Struct {
	return new(Tasks)
}

// NewRecord makes a new record for that table.
func (v *tasksTableType) NewRecord() reform.Record {
	return new(Tasks)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *tasksTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// TasksTable represents Tasks view or table in SQL database.
var TasksTable = &tasksTableType{
	s: parse.StructInfo{
		Type:    "Tasks",
		SQLName: "Tasks",
		Fields: []parse.FieldInfo{
			{Name: "Id", Type: "uuid.UUID", Column: "Id"},
			{Name: "ProjectId", Type: "uuid.UUID", Column: "ProjectId"},
			{Name: "TaskTitle", Type: "string", Column: "TaskTitle"},
			{Name: "TaskDescription", Type: "*string", Column: "TaskDescription"},
		},
		PKFieldIndex: 0,
	},
	z: new(Tasks).Values(),
}

// String returns a string representation of this struct or record.
func (s Tasks) String() string {
	res := make([]string, 4)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "ProjectId: " + reform.Inspect(s.ProjectId, true)
	res[2] = "TaskTitle: " + reform.Inspect(s.TaskTitle, true)
	res[3] = "TaskDescription: " + reform.Inspect(s.TaskDescription, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Tasks) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.ProjectId,
		s.TaskTitle,
		s.TaskDescription,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Tasks) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.ProjectId,
		&s.TaskTitle,
		&s.TaskDescription,
	}
}

// View returns View object for that struct.
func (s *Tasks) View() reform.View {
	return TasksTable
}

// Table returns Table object for that record.
func (s *Tasks) Table() reform.Table {
	return TasksTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Tasks) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Tasks) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Tasks) HasPK() bool {
	return s.Id != TasksTable.z[TasksTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Id = pk.
func (s *Tasks) SetPK(pk interface{}) {
	reform.SetPK(s, pk)
}

// check interfaces
var (
	_ reform.View   = TasksTable
	_ reform.Struct = (*Tasks)(nil)
	_ reform.Table  = TasksTable
	_ reform.Record = (*Tasks)(nil)
	_ fmt.Stringer  = (*Tasks)(nil)
)

func init() {
	parse.AssertUpToDate(&TasksTable.s, new(Tasks))
}
