// Code generated by gopkg.in/reform.v1. DO NOT EDIT.

package models

import (
	"fmt"
	"github.com/google/uuid"
	"strings"

	"gopkg.in/reform.v1"
	"gopkg.in/reform.v1/parse"
)

type usersTableType struct {
	s parse.StructInfo
	z []interface{}
}

// Schema returns a schema name in SQL database ("").
func (v *usersTableType) Schema() string {
	return v.s.SQLSchema
}

// Name returns a view or table name in SQL database ("Users").
func (v *usersTableType) Name() string {
	return v.s.SQLName
}

// Columns returns a new slice of column names for that view or table in SQL database.
func (v *usersTableType) Columns() []string {
	return []string{
		"Id",
		"Name",
		"Surname",
		"Nickname",
		"RoleId",
		"Password",
	}
}

// NewStruct makes a new struct for that view or table.
func (v *usersTableType) NewStruct() reform.Struct {
	return new(Users)
}

// NewRecord makes a new record for that table.
func (v *usersTableType) NewRecord() reform.Record {
	return new(Users)
}

// PKColumnIndex returns an index of primary key column for that table in SQL database.
func (v *usersTableType) PKColumnIndex() uint {
	return uint(v.s.PKFieldIndex)
}

// UsersTable represents Users view or table in SQL database.
var UsersTable = &usersTableType{
	s: parse.StructInfo{
		Type:    "Users",
		SQLName: "Users",
		Fields: []parse.FieldInfo{
			{Name: "Id", Type: "uuid.UUID", Column: "Id"},
			{Name: "Name", Type: "string", Column: "Name"},
			{Name: "Surname", Type: "string", Column: "Surname"},
			{Name: "Nickname", Type: "string", Column: "Nickname"},
			{Name: "RoleId", Type: "uuid.UUID", Column: "RoleId"},
			{Name: "Password", Type: "string", Column: "Password"},
		},
		PKFieldIndex: 0,
	},
	z: new(Users).Values(),
}

// String returns a string representation of this struct or record.
func (s Users) String() string {
	res := make([]string, 6)
	res[0] = "Id: " + reform.Inspect(s.Id, true)
	res[1] = "Name: " + reform.Inspect(s.Name, true)
	res[2] = "Surname: " + reform.Inspect(s.Surname, true)
	res[3] = "Nickname: " + reform.Inspect(s.Nickname, true)
	res[4] = "RoleId: " + reform.Inspect(s.RoleId, true)
	res[5] = "Password: " + reform.Inspect(s.Password, true)
	return strings.Join(res, ", ")
}

// Values returns a slice of struct or record field values.
// Returned interface{} values are never untyped nils.
func (s *Users) Values() []interface{} {
	return []interface{}{
		s.Id,
		s.Name,
		s.Surname,
		s.Nickname,
		s.RoleId,
		s.Password,
	}
}

// Pointers returns a slice of pointers to struct or record fields.
// Returned interface{} values are never untyped nils.
func (s *Users) Pointers() []interface{} {
	return []interface{}{
		&s.Id,
		&s.Name,
		&s.Surname,
		&s.Nickname,
		&s.RoleId,
		&s.Password,
	}
}

// View returns View object for that struct.
func (s *Users) View() reform.View {
	return UsersTable
}

// Table returns Table object for that record.
func (s *Users) Table() reform.Table {
	return UsersTable
}

// PKValue returns a value of primary key for that record.
// Returned interface{} value is never untyped nil.
func (s *Users) PKValue() interface{} {
	return s.Id
}

// PKPointer returns a pointer to primary key field for that record.
// Returned interface{} value is never untyped nil.
func (s *Users) PKPointer() interface{} {
	return &s.Id
}

// HasPK returns true if record has non-zero primary key set, false otherwise.
func (s *Users) HasPK() bool {
	return s.Id != UsersTable.z[UsersTable.s.PKFieldIndex]
}

// SetPK sets record primary key, if possible.
//
// Deprecated: prefer direct field assignment where possible: s.Id = pk.
func (s *Users) SetPK(pk interface{}) {
	reform.SetPK(s, pk.(uuid.UUID))
}

// check interfaces
var (
	_ reform.View   = UsersTable
	_ reform.Struct = (*Users)(nil)
	_ reform.Table  = UsersTable
	_ reform.Record = (*Users)(nil)
	_ fmt.Stringer  = (*Users)(nil)
)

func init() {
	parse.AssertUpToDate(&UsersTable.s, new(Users))
}
