Sql:
  #Host: 192.168.1.134
  Host: localhost
  Port: 1433
  User: "admin"
  Pass: "Kot_456789"
  Name: "sqlserver"
  Db: "mainDb"
Jwt:
  Enable: True
  ExpiresAt: 0
Api:
  Address: "localhost"
  Port: 8080